name: GitHub Releases

on:
  push:
    tags:
      - "*"

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Parse Changelog
        id: changelog
        uses: ocavue/changelog-parser-action@v1
      - uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          body: ${{ steps.changelog.outputs.latestBody }}
